/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class chamberofsecrets_HelloJNI */

#ifndef _Included_chamberofsecrets_HelloJNI
#define _Included_chamberofsecrets_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     chamberofsecrets_HelloJNI
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_chamberofsecrets_HelloJNI_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
